%YAML 1.1
---
name: CLI Assistant
version: 1.0.0
schema: v1

models:
  - name: gpt-oss 20b
    provider: ollama
    model: gpt-oss:latest
    roles:
      - apply
      - chat
      - edit
    capabilities:
      - tool_use

rules:
  - Unless otherwise specified, assume I have foundational knowledge of the subject in question.
  - Provide concise answers, unless I ask for a more detailed explanation.
